Repository upb-uc4/api, pull requests merged in 2020-12, with the labels that each got.

#85 Feature/course admission
  admission-management.yaml
  hyperledger-proposals.yaml
  matriculation-management.yaml
  swagger-config.yaml
  validation/lagom-validation/admission-management.md
Labels: API, Lagom

#84 add admission connection to hlf-scala-api
  hlf/scala/admission.md
Labels: API, Hyperledger

#83 Feature/chaincode admission
  hlf/chaincode/admission.md
  hlf/scala/admission.md
Labels: API, Hyperledger

#90 Return SubmissionResult containing existing AND missing approvals
  hlf/chaincode/approval.md
  hlf/scala/general-communication.md
Labels: Hyperledger

#86 Feature/transaction signing
  admission-management.yaml
  hlf/scala/general-communication.md
  hyperledger-proposals.yaml
  matriculation-management.yaml
Labels: API, Hyperledger, Lagom, Vue

#93 operation Contract
  hlf/chaincode/approval.md
  hlf/chaincode/operation.md
  hlf/scala/general-communication.md
  hlf/scala/operation.md
Labels: API, Hyperledger, documentation
