Repository upb-uc4/api, pull requests merged in 2020-08, with the labels that each got.

#17 Migrate password change endpoint
  authentication-management.yaml
  user-management.yaml
Labels: API

#19 Feature/hyperledger lagom api
  hyperledger_course_api.md
  hyperledger_matriculation_api.md
  matriculation-management.yaml
  user-management.yaml
Labels: API

#20 Fix endpoint path in matriculation api, fix matriculation api not bei…
  matriculation-management.yaml
  swagger-config.yaml
Labels: API

#21 Add proper error import to authentication and matriculation management
  authentication-management.yaml
  course-management.yaml
  hl-course-management.yaml
  matriculation-management.yaml
  user-management.yaml
Labels: API

#22 Add query to fetch multiple users to getUsers
  user-management.yaml
Labels: API

#23 Adjust api to be consistent with chaincode errors
  hyperledger_matriculation_api.md
Labels: API

#25 Add phoneNumber
  user-management.yaml
Labels: API

#26 Add new errors for failing deserilization
  authentication-management.yaml
  course-management.yaml
  errors.yaml
  hl-course-management.yaml
  matriculation-management.yaml
  user-management.yaml
Labels: API

#30 Adapt API to JWT authentication
  authentication-management.yaml
  course-management.yaml
  errors.yaml
  matriculation-management.yaml
  user-management.yaml
Labels: API, Lagom, Vue

#33 Add detailed specification for name of invalidParam in DetailedError
  hyperledger_matriculation_api.md
Labels: API, Hyperledger, enhancement, help wanted

#36 Add transient specification
  hyperledger_matriculation_api.md
Labels: API, Hyperledger

#34 Updated user-management.yaml to reflect the newly merged endpoints
  user-management.yaml
Labels: API, Lagom, Vue

#35 Multiple fields of study/semesters addEntryToMatriculationData
  hyperledger_matriculation_api.md
Labels: API, Hyperledger, Lagom, Vue, help wanted
