Repository upb-uc4/api, pull requests merged in 2020-11, with the labels that each got.

#67 Feature/hyperledger po
  hlf/chaincode/examination-regulation.md
Labels: API, Hyperledger, enhancement

#72 Update unsigned.md
  hlf/scala/unsigned.md
Labels: Hyperledger, Lagom

#71 add documentation on input checks for hlf contracts
  hlf/chaincode/approval.md
  hlf/chaincode/certificate.md
  hlf/chaincode/examination-regulation.md
  hlf/chaincode/matriculation.md
Labels: Hyperledger, documentation

#73 Provide error message to regexes in configuration service
  configuration-management.yaml
Labels: Lagom, Vue

#68 Add exam reg management yaml
  course-management.yaml
  exam-reg-management.yaml
  validation/lagom-validation/course-management.md
  validation/lagom-validation/examreg-management.md
Labels: API, Lagom, Vue

#74 refactor/post message user into develop
  user-management.yaml
Labels: API, Lagom, Vue

#59 Add governmentId to User Object
  user-management.yaml
Labels: API, Lagom, Vue

#82 Remove fields of study from configuration object
  configuration-management.yaml
  matriculation-management.yaml
  validation/lagom-validation/matriculation-management.md
Labels: API, Lagom, Vue

#76 feature/ user deletion
  user-management.yaml
Labels: API, Lagom, Vue
