Repository upb-uc4/api, pull requests merged in 2020-10, with the labels that each got.

#56 Feature/chaincode arg name
  hlf_chaincode_api_matriculation.md
Labels: API, Hyperledger

#55 Add ValidationTimeout to api
  course-management.yaml
  errors.yaml
  matriculation-management.yaml
  user-management.yaml
Labels: API, Lagom, Vue

#58 Change matriculationData to include the new pseudonymisation
  matriculation-management.yaml
Labels: API, Lagom, Vue

#57 Adapt documentation for validation in lagom
  validation/lagom-validation/authentication-management.md
  validation/lagom-validation/course-management.md
  validation/lagom-validation/matriculation-management.md
  validation/lagom-validation/user-management.md
Labels: API, Lagom, Vue

#48 Feature/certificate management
  certificate-management.yaml
  errors.yaml
  swagger-config.yaml
Labels: API, Lagom, Vue

#61 Bugfix/certificate
  certificate-management.yaml
Labels: API, Lagom, Vue

#63 update hlf-documents
  hlf/chaincode/certificate.md
  hlf/chaincode/errors.md
  hlf/chaincode/matriculation.md
  hlf/scala/certificate.md
  hlf/scala/errors.md
  hlf/scala/matriculation.md
  hlf_chaincode_api_course.md
Labels: Hyperledger, documentation

#64 Add api for getting and submitting unsigned transactions
  matriculation-management.yaml
Labels: Lagom

#62 Feature/utility service
  configuration-management.yaml
  errors.yaml
Labels: API, Lagom, Vue

#65 first draft contract API
  hlf/chaincode/approval.md
Labels: Hyperledger

#66 first draft at Unsigned Transaction API
  hlf/scala/unsigned.md
Labels: Hyperledger
