Repository upb-uc4/api, pull requests merged in 2020-09, with the labels that each got.

#38 add info for hlf-api
  .gitignore
  hlf-api-matriculation.md
  hyperledger_matriculation_api.md
Labels: Hyperledger, Lagom

#37 Change error type
  .gitignore
  authentication-management.yaml
  course-management.yaml
  errors.yaml
  hyperledger_matriculation_api.md
  matriculation-management.yaml
  user-management.yaml
Labels: API

#39 Refactor invalidParams naming scheme
  hyperledger_matriculation_api.md
Labels: API

#45 Add endpoints for GET and PUT images
  errors.yaml
  user-management.yaml
Labels: API, Lagom, Vue

#46 Bugfix/validation fix
  course-management.yaml
  user-management.yaml
Labels: API, Lagom, Vue

#47 Add new "RefreshTokenMissing" error to api
  authentication-management.yaml
  errors.yaml
Labels: API, Lagom, Vue

#52 update hlf-api-document
  hlf-api-matriculation.md
Labels: API, Hyperledger

#53 Update UserService api to include new DELETE Image call
  user-management.yaml
Labels: API, Lagom, Vue

#54 Certificates on Chain and Refactoring
  hlf-api-matriculation.md
  hlf_chaincode_api_certificate.md
  hlf_chaincode_api_course.md
  hlf_chaincode_api_errors.md
  hlf_chaincode_api_matriculation.md
  hlf_scala_api_certificate.md
  hlf_scala_api_errors.md
  hlf_scala_api_matriculation.md
Labels: Hyperledger, documentation, enhancement
