Repository upb-uc4/api, pull requests merged in 2021-03, with the labels that each got.

#115 Generalize ApprovalDenied/RejectionDenied to ParticipationDenied
  hlf/chaincode/contracts/admission.md
  hlf/chaincode/contracts/exam.md
  hlf/chaincode/contracts/examResult.md
  hlf/chaincode/contracts/group.md
  hlf/chaincode/contracts/matriculation.md
  hlf/chaincode/contracts/operation.md
  hlf/chaincode/errors.md
Labels: Hyperledger, enhancement

#116 add new systemTime Error for all transactions
  hlf/chaincode/errors.md
Labels: API, enhancement

#117 feature/transcript_of_records into develop
  report-management.yaml
Labels: API, Lagom, Vue
