Repository upb-uc4/api, pull requests merged in 2021-01, with the labels that each got.

#87 Add Hyperledger version endpoints
  admission-management.yaml
  authentication-management.yaml
  certificate-management.yaml
  configuration-management.yaml
  course-management.yaml
  examreg-management.yaml
  matriculation-management.yaml
  user-management.yaml
Labels: API, Lagom, Vue

#94 Feature/gdpr
  report-management.yaml
  swagger-config.yaml
  user-management.yaml
Labels: API, Lagom, Vue

#97 Fix api url being incorrect in 5 api definitions
  admission-management.yaml
  authentication-management.yaml
  certificate-management.yaml
  configuration-management.yaml
  course-management.yaml
  examreg-management.yaml
  matriculation-management.yaml
  user-management.yaml
Labels: API, Lagom, Vue

#95 Add group management api
  group-management.yaml
  swagger-config.yaml
Labels: API, Lagom, Vue

#98 Add new error, for when wrong number of parameters is received
  hlf/chaincode/operation.md
  hlf/scala/operation.md
Labels: API, Hyperledger, Lagom

#101 Add examination regulation filter to getCourses endpoint
  course-management.yaml
Labels: API, Lagom, Vue

#106 Add insufficient approvals error to addMatriculationData and addEntri…
  hlf/chaincode/matriculation.md
  hlf/chaincode/operation.md
Labels: Hyperledger, bug
