Repository upb-uc4/api, pull requests merged in 2021-02, with the labels that each got.

#105 Feature/chaincode exams
  hlf/chaincode/admission.md
  hlf/chaincode/exam.md
  hlf/chaincode/examResult.md
  hlf/scala/admission.md
  hlf/scala/exam.md
  hlf/scala/examResult.md
Labels: API, Hyperledger, Lagom, enhancement

#99 refactor/move_frontend_signing into develop
  hlf/chaincode/access-rights.md
  hlf/chaincode/admission.md
  hlf/chaincode/group.md
  hlf/chaincode/matriculation.md
  hlf/chaincode/operation.md
  hlf/scala/general-communication.md
  hlf/scala/operation.md
Labels: API, Hyperledger, Lagom

#104 New operation workflow, Operations 1.1
  admission-management.yaml
  matriculation-management.yaml
  operation-management.yaml
Labels: API, Lagom

#107 feature/frontend_exam into develop
  admission-management.yaml
  certificate-management.yaml
  configuration-management.yaml
  exam-management.yaml
  exam-result-management.yaml
Labels: API, Lagom, Vue

#108 Add operation not pending error
  hlf/chaincode/admission.md
  hlf/chaincode/matriculation.md
  hlf/chaincode/operation.md
Labels: Hyperledger, bug

#111 Feature/operation not pending error
  hlf/chaincode/operation.md
Labels: API, bug
